### ISSUE TITLE
Evaluation Performance in Phase2.

### ISSUE THREAD

**Issue by XiaoBuL** [HL-hanlin/SMKD#1]
Hello,

Thanks for your great work! I wonder if the model you released is correct. 

I download the phase2 pre-trained model on miniImageNet and evaluate it with the script you provide:

- **prototype**:
```sh
python eval_smkd.py --server mini --num_shots 5 --ckp_path /root/autodl-nas/FSVIT_results/MINI480_phase2 --ckpt_filename checkpoint0040.pth --output_dir /root/autodl-nas/FSVIT_results/MINI480_prototype --evaluation_method cosine --iter_num 10000
```

The 1-shot and 5-shot performance is 68.35% +- 0.18% and 85.20% +- 0.10%, respectively..

**Comment by HL-hanlin** [comment]
Hi! Thanks for your interest in our work!

I double-checked the checkpoint file and re-evaluated it on my computer. It works as expected: 1 shot: 74.28, 5 shot: 88.82.

![image](https://user-images.githubusercontent.com/62345469/230445877-143ba366-d6c6-47e4-a69b-72e773ef6a81.png)
![image](https://user-images.githubusercontent.com/62345469/230445454-17baf85b-8c40-48a0-b821-8a53351b87f9.png)

I guess one possible reason for the discrepancy could be that the mini-ImageNet dataset we used has a resolution of 480x480. You can use the repository [mini-ImageNet tools](https://github.com/y2l/mini-imagenet-tools) and set the argument --image_resize 480 to generate the same resolution that we used.

Please let me know if this helps, and I'm more than happy to discuss further if you still encounter any issues!
